version: '3.1'

services:
  db:
    image: mysql:oracle
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projfbd
      MYSQL_USER: fbd
      MYSQL_PASSWORD: fbd
    ports:
      - 3306:3306
    volumes:
      - mysql-dados:/var/lib/mysql
volumes: # permite que os dados sejam persistidos mesmo que o container seja removido no fs wsl2
  mysql-dados:
    name: mysql-dados