-- Active: 1684245138463@@127.0.0.1@3306@projfbd

-- ============= CRIANDO PROCEDURE =========================

DELIMITER $$

CREATE PROCEDURE IF NOT EXISTS PROC_SELECIONAR_RAIS_POR_ANO
(IN ANO INT) BEGIN
	SELECT * FROM RAIS as r WHERE ANO = r.ano;
END;

$$

DELIMITER;

CALL PROC_SELECIONAR_RAIS_POR_ANO (2018);

-- GERAR VALORES DO describe DO PANDAS

DELIMITER $$
